const cards = [
    {
        image: "/Images/2.Komunia.jpg",
        parable_text: `Człowiek żyje jako wyspa i stąd bierze się  wszelka niedola. Przez całe stulecia człowiek usiłował żyć niezależny od egzystencji -  co z samej swojej natury nie jest możliwe. Człowiek nie może być ani niezależny, ani zależny. Egzystencja jest stanem wzajemnej zależności, wszystko zależne jest od wszystkiego. Nie ma hierarchii, nikt nie jest niższy i nikt nie jest wyższy. Egzystencja jest komunią, wiecznym zakochaniem. Problemy stwarza sama myśl, że człowiek musi być wyższy, lepszy, specjalny. Człowiek musi być niczym !  Musi rozpuścić się w totalności wszystkiego, co istnieje. A gdy porzucimy wszystkie bariery, następuje komunia, która jest błogosławieństwem. Bycie jednością, ze wszystkim, co istnieje -  oto wszystko. Oto jest najgłębszy rdzeń religijności.`,
        parable_sound: "/Parable Sound/2.KomuniaParable.mp3",
        explantation_text: `Heraklit mówi: Gdyby działo się tak jak człowiek chce, nie byłoby lepiej niż jest. Póki nie oczekujesz tego, co nieoczekiwane, nie znajdziesz prawdy, trudno jest ją bowiem odkryć i dostąpić. Natura uwielbia się ukrywać. Pan, którego wyrocznia jest w Delfach, nie mówi i nie ukrywa, daje tylko znaki.
        Egzystencja nie ma języka, jeśli będziesz zależny od języka, nie będzie kontaktu z egzystencją. Egzystencja jest tajemnicą, nie można jej interpretować: jeśli to zrobisz, wszystko przegapisz. Egzystencję można przeżywać, ale nie można o niej myśleć. Przypomina ona raczej poezję niż filozofię. Jest znakiem, drzwiami. Pokazuje, ale nic nie mówi. Przez umysł nie można dotrzeć do egzystencji. Jeśli będziesz o niej myślał nie dotrzesz do niej, bo samo myślenie jest barierą. Myślenie jest twoim prywatnym światem, należy do ciebie, jesteś w nim zamknięty, uwięziony w samym sobie. Gdy nie myślisz, nie ma cię: nie jesteś już zamknięty. Otwierasz się egzystencja wpływa w ciebie, a ty wpływasz w egzystencję.
        Naucz się słuchać. Suchanie oznacza, że jesteś otwarty, podatny, przyjmujący, ale nie myślisz. Myślenie jest działaniem pozytywnym. Słuchanie jest biernością, stajesz się jak dolina i przyjmujesz, stajesz się jak łono i przyjmujesz. Jeśli zdołasz słuchać, natura przemówi, ale nie językiem. Natura nie używa słów. Czego więc używa natura? Heraklit powiada, że używa znaków. Kwiat - jaki znak jest w nim zawarty? Kwiat nic nie mówi, ale czy naprawdę można to stwierdzić? Mówi bardzo wiele, ale nie używa słów - to przesłanie bez słów.
        Aby usłyszeć to, co bez słów, sam musisz stać się istnieniem bez słów, gdyż tylko identyczności mogą się usłyszeć, tylko identyczności mogą wejść ze sobą w kontakt. Gdy siedzisz obok kwiatu, nie bądź osobą bądź kwiatem. Siedząc pod drzewem, nie bądź osobą bądź drzewem. Kąpiąc się w rzece, nie bądź człowiekiem bądź rzeką. Dostaniesz miliony znaków. I nie jest to kontakt, ale komunia. Natura mówi tysiącami  języków, nie jednym językiem.`,
        explantation_sound: "/Explantation Sound/2.KomuniaExplantation.mp3"
    },
    {
        image: "/Images/6.Chciwość.jpg",
        parable_text: `Przypowieść ambicji i pośpiechu.
        Zawsze wtedy, gdy ludzie stają się bardzo chciwi, zaczynają się bardzo spieszyć i stale znajdują nowe sposoby na nabranie jeszcze większej szybkości. Ciągle są w biegu, ponieważ zdaje im się, że życie ucieka. To ci ludzie mówią, że czas to pieniądz. Czas to pieniądz? Pieniądze są bardzo ograniczone; czas jest nieograniczony. Czas to nie pieniądz, czas jest wiecznością - jest od zawsze i zawsze będzie. Ty też istniejesz od zawsze i będziesz istnieć zawsze. 
        Porzuć, więc chciwość i nie przejmuj się rezultatami. Czasami przez swoją niecierpliwość wiele przegapiamy.`,
        parable_sound: "/Parable Sound/6.ChciwośćParable.mp3",
        explantation_text: `Jest taka dawna hinduska przypowieść. Pewien wielki Święty Narada szedł do raju. Narada podróżował między rajem i ziemią. Był kimś w rodzaju posłańca między tym światem i tamtym - był pomostem. Spotkał starego Mędrca bardzo starego, który siedział pod drzewem i powtarzał swoją mantrę. Powtarzał tę mantrę od wielu lat i wielu żywotów. Narada zapytał go. Czy chciałbyś o coś poprosić? Czy chciałbyś przekazać coś Panu? Starzec otworzył oczy i rzekł. Zapytaj tylko o jedno. Jak długo mam jeszcze czekać? Jak długo? Powiedz mu, że to zbyt wiele. Od wielu żywotów powtarzam tę mantrę. Jak długo mam to jeszcze robić? Jestem już zmęczony. Jestem znużony. Niedaleko tego wiekowego mędrca pod innym drzewem widać było tańczącego młodzieńca grającego na ektara  na jedno strunowym instrumencie. Narada zapytał go żartobliwie. Czy ty też chciałbyś dowiedzieć się, ile jeszcze czasu trzeba, by nastąpiło twoje oświecenie? Młodzieniec nawet się nie odezwał tańczył. Idę do pana, czy chcesz mu coś przekazać? Ponowił pytanie Narada. Młodzieniec roześmiał się i dalej tańczył. Po paru dniach Narada wrócił i rzekł do Starca. Bóg powiedział, że musisz poczekać jeszcze przynajmniej trzy żywoty. Starzec tak się rozzłościł, że rzucił swój różaniec. Prawie chciał pobić Naradę. To bzdura. Czekam i czekam. Robię wszelkiego rodzaju wyrzeczenia. Intonuję, poszczę, odprawiam wszelkie rytuały. Spełniłem wszystkie wymagania. Trzy żywoty to niesprawiedliwe. Młodzieniec nadal tańczył radośnie pod drzewem. Narada z obawą podszedł do niego? Chociaż o to nie prosiłeś, zapytałem z mojej własnej ciekawości. Kiedy Bóg powiedział mi, że ten starzec musi poczekać jeszcze trzy żywoty, zapytałem o młodzieńca, który tańczy i gra na swoim ektara. A Bóg rzekł. Ten młody człowiek będzie musiał czekać tyle żywotów, ile jest liści na drzewie, pod którym on tańczy. Młodzieniec zaczął tańczyć jeszcze szybciej. Tylko tyle liści, co na tym jedynym drzewie. To nie tak długo już prawie dotarłem. Pomyśl, ile jest drzew na całej Ziemi porównaj. A tak to już bardzo blisko. Dziękuję ci, że zapytałeś o mnie? I znowu zaczął tańczyć. Opowieść głosi, że młodzieniec dostąpił oświecenia natychmiast w tej właśnie chwili.`,
        explantation_sound: "/Explantation Sound/6.ChciwośćExplantation.mp3"
    },
    {
        image: "/Images/24.Nadużywanie.jpg",
        parable_text: `Jak Vivekananda stracił klucz.
        Jedynym antidotum na nadużywanie mocy psychicznych jest miłość. Tak. Jeśli jej nie ma, władza wszystko zniszczy. Bogactwo, prestiż, polityka czy psychika -  nie ma to znaczenia. Zawsze wtedy, gdy czujesz się silny jeżeli nie masz miłości jako antidotum, twoja władza stanie się przekleństwem dla innych, ponieważ władza zaślepia. Miłość otwiera oczy, oczyszcza oczy... Twoje widzenie staje się czyste.`,
        parable_sound: "/Parable Sound/24.NadużywanieWładzyParable.mp3",
        explantation_text: `W ashramie Ramakrishny w Dakshineshwar, w Kalkucie było wielu uczniów, a Vivekananda był jednym z najbardziej intelektualnych.
        Był tam też bardzo prosty człowiek, który również był uczniem. Nazywał się Kalu, biedak. Był tak wierny religijny, emocjonalny, że miał w swoim pokoju setki posążków różnych bogów. Wczesnym rankiem kąpał się w Gangesie, potem czcił te bożki. Oczywiście każdego musiał czcić po równo, bo któryś mógłby poczuć się urażony. Tak mijały Kalu całe dnie, zaś wszyscy śmiali się z niego: “Co ty robisz? Jeden bóg wystarcza !”.
        Vivekananda najbardziej celował w naigrywaniu się z Kalu:- Jesteś po prostu głupi, to przecież tylko kamienie ! A ty marnujesz swoje życie. Ale Kalu nikogo nie słuchał: dalej robił swoje. Pewnego dnia Ramakrishna dał Vivekanandzie pewną metodę praktykowania uważności: “Idź do swojego pokoju, zamknij drzwi i praktykuj ją.” Gdy Vivekananda doszedł do pewnego etapu, poczuł się tak pełny władzy, że przyszła mu myśl: “Jeśli teraz powiem w myśli do Kalu, żeby wziął wszystkie swoje bożki i wrzucił je do Gangesu, zrobi to.” I tak też zrobił. Siedząc w swoim pokoju powiedział w głębi siebie: “Kalu zbierz wszystkie swoje bożki i wrzuć je do Gangesu.”
        Kalu zebrał wszystkie bożki do jednej wielkiej torby i zaczął je ciągnąć po schodach. Ramakrishna pobiegł za nim i zapytał go: 
        “Co robisz?”
        Nagle usłyszałem głos - odrzekł Kalu - musiał przyjść od samego Boga, bo nikogo nie było w pokoju. Głos powiedział:  “Kalu zbierz wszystkie swoje bożki i wrzuć je do Gangesu.” Był tak potężny, że nie mogłem w niego wątpić. 
        Chodź weź z powrotem swoje bożki - rzekł Ramakrishna. -  Pokażę ci, skąd był ten głos.
        Zapukał do Vivekanandy, który wyszedł z pokoju. Ramakrishna był bardzo rozzłoszczony. Vivekananda to jest ostatnia rzecz, jakiej mogłem spodziewać się po tobie. Mówiłem, żebyś był uważny, a nie niszczył życie tego biedaka. On jest tak prostoduszny i kochający, to taki piękny człowiek, jak możesz mu to robić ? Od tej pory nigdy nie dostąpisz takiej samej władzy. Tak jak powiedział Vivekananda zmarł, nie dostąpiwszy oświecenia. Mimo że stał się sukcesorem Ramakrishny, ponieważ był wielkim mówcą, miał pewną charyzmę i wpływ na ludzi … sam zmarł jako biedak, nic nie wiedząc. Powodem było to, że zakłócił życie tego prostodusznego człowieka, gdy dostał odrobinę władzy i natychmiast jej użył - nie dla korzyści, ale po to, by komuś zaszkodzić.`,
        explantation_sound: "/Explantation Sound/24.NadużywanieWŁadzyExplantation.mp3",
    },
    {
        image: "/Images/29.Wdzięczność.jpg",
        parable_text: `Noc bez dachu nad głową
        Gdy człowiek potrafi odczuć wdzięczność i za ból i za przyjemność bez rozróżniania i wybierania odczuwając wdzięczność za wszystko co jest mu dawane. Skoro to Bóg daje musi mieć jakiś powód ku temu. Może nam się to podobać albo nie, ale musi to być potrzebne dla naszego wzrastania. Zima i lato są tak samo potrzebne do wzrastania. Kiedy to odczucie zagości w sercu, każda chwila życia jest wdzięcznością. Niech stanie się to twoją medytacją i modlitwą: dziękuj Bogu za każdą chwilę - za śmiech, za łzy, za wszystko. Zobaczysz narastającą ciszę w swoim sercu, której wcześniej nie znałeś. To jest błogość. Pierwszą rzeczą jest zaakceptowanie życia takim jakim ono jest. Kiedy je zaakceptujesz, znikają pragnienia, napięcia i niezadowolenie; kiedy zaakceptujesz je takim, jakim ono jest, zaczynasz czuć się bardzo radosny i to bez żadnego powodu! Kiedy radość ma jakiś powód, nie będzie trwać długo. Kiedy radość nie ma żadnego powodu, będzie trwać wiecznie.`,
        parable_sound: "/Parable Sound/29.WdzięcznośćParable.mp3",
        explantation_text: `Zdarzyło się to w życiu bardziej sławnej kobiety Zen, miała na imię Rengetsu. Bardzo niewiele kobiet dostąpiło Najwyższego w Zen. Ona jest jedną z tych kilku kobiet. Była na pielgrzymce. o zachodzie słońca dotarła do wioski, prosiła więc o nocleg, ale mieszkańcy pozamykali drzwi. Byli przeciwni Zen. Zen jest tak rewolucyjny i buntowniczy, że zaakceptowanie go przychodzi bardzo trudno. Jeśli go zaakceptujesz, zostaniesz przemieniony, przejdziesz przez ogień, nigdy nie będziesz już taki, jak kiedyś. Ludzie tradycyjni zawsze byli przeciwni wszystkiemu, co jest prawdziwe w religii. Tradycja oznacza wszystko to, co w religii jest nieprawdziwe. W tej wiosce musieli więc mieszkać tradycjonalni buddyści i nie pozwolili tej kobiecie na pozostanie, wyrzucili ją. Noc była zimna, a ta stara kobieta bez dachu nad głową … i głodna. Było Naprawdę zimno nie spała dobrze. By 8 6 też niebezpiecznie... dzikie zwierzęta i cała ta sytuacja. W  środku nocy obudziła się, była bardzo zmarznięta, zobaczyła na wiosennym nocnym niebie kwiaty wiśni w pełnym rozkwicie, śmiejące się do zamglonego księżyca. Zauroczona pięknem,  wstała i złożyła pokłon w kierunku wioski:
        Dzięki ich uczynności
        gdy odmówili mi noclegu
        znalazłam się pod kwiatami
        nocą tego zamglonego księżyca.
        Odczuła wdzięczność. Z wielką wdzięcznością podziękowała tym, którzy odmówili jej schronienia, bo inaczej spałaby pod zwykłym dachem i przegapiłaby to błogosławieństwo, kwiaty wiśni i szeptanie do zamglonego księżyca, ten spokój nocy i tę największą ciszę. Nie złości się, akceptuje to. Nie tylko akceptuje ale jeszcze wychodzi temu na powitanie.. Czuje wdzięczność. Człowiek staje się Buddą gdy z wdzięcznością akceptuje wszystko, co życie mu przynosi.`,
        explantation_sound: "/Explantation Sound/29.WdzięcznośćExplantation.mp3",
    },
    {
        image: "/Images/33.Odnowa.jpg",
        parable_text: `Dziedzictwo Buddy.
        Gdy nie ma przeszłości i nie ma przyszłości, tylko wtedy jest spokój. Przyszłość oznacza aspiracje, osiąganie, cele ambicje oraz pragnienia. Nie można być tu i teraz, zawsze za czymś biegniesz, gdzieś indziej niż jesteś. Człowiek musi być całkowicie obecny w teraźniejszości, wtedy jest pokój. Z niego bierze się odnowa życia, gdyż życie zna tylko jeden czas – tym czasem jest teraźniejszość. Przeszłość jest śmiercią, przyszłość jest tylko projekcją martwej przeszłości. Co możesz myśleć o przyszłości?  Myślisz kategoriami przeszłości, tego co już znasz i rzutujesz to, rzecz jasna w lepszy sposób. Piękniejsze, bardziej udekorowane... znikły bóle i pozostają tylko przyjemności, ale i tak jest to przeszłość.  Przeszłości nie ma, przyszłości nie ma, jest tylko teraźniejszość. Bycie w teraźniejszości oznacza bycie żywym człowiekiem, optymalnym - na tym polega odnowa.`,
        parable_sound: "/Parable Sound/33.OdnowaParable.mp3",
        explantation_text: `Zaledwie jeden dzień, zanim Gautama Budda opuścił swój pałac w poszukiwaniu prawdy, jego żona urodziła dziecko. To bardzo ludzka opowieść, piękna... przed opuszczeniem pałacu chciał choć zobaczyć twarz swego dziecka, symbol jego miłości do żony. Poszedł więc do komnaty żony. Spała. Dziecko było okryte kocem. Chciał zdjąć koc i popatrzeć na twarz dziecka, bo może nigdy miał już nie wrócić. Wyruszał w nieznane. Królestwo, żonę, dziecko, siebie - wszystko ryzykował w poszukiwaniu oświecenia, czegoś, o czym tylko słyszał jako o pewnej możliwości, która zdarzyła się wcześniej kilku ludziom jej szukającym. Był pełny wątpliwości, jak każdy z nas, ale chwila decyzji nadeszła. Był zdeterminowany, musiał iść. Ten ludzki umysł i natura jednak... Tylko chciał popatrzeć, nie widział jeszcze twarzy własnego dziecka. Bał się, że gdy odsunie koc, a  Yashodhara, jego żona obudzi się, zapyta: “Co robisz w środku nocy w moim pokoju? Wygląda jakbyś gdzieś się wybierał.”
        Za bramą stał już rydwan. Wszystko było gotowe, pozostało tylko wyjść z pałacu. Woźnicy powiedział przecież: “Czekaj na mnie tylko minutę. Zobaczę tylko twarz mojego dziecka. Może nigdy już nie wrócę.” Nie mógł spojrzeć, bał się, że jeśli Yashodhara zbudzi się, zacznie płakać: “Dokąd idziesz? Co robisz? Po co to wyrzeczenie? Co to jest to oświecenie?” Z kobietą nigdy nie wiadomo, mogła by zbudzić cały pałac! Przyjdzie ojciec i wszystko się skończy. Tak więc po prostu uciekł...
        Po dwunastu latach, gdy był już człowiekiem oświeconym, pierwszym co zrobił, był powrót do pałacu i przeproszenie ojca żony i syna, który miał wtedy 12 lat. Wiedział, że będą w złości. Ojciec był rozzłoszczony. Jego pierwszego spotkał. Przez pół godziny wymyślał Buddzie. Nagle uświadomił sobie, że mówi tyle rzeczy, a jego syn stoi przed nim, jak marmurowy posąg, jak jakby nic go nie dotykało. Ojciec spojrzał na niego, a Gautama Budda powiedział: “Tego chciałem. Osusz proszę łzy. Przyjrzyj się: “nie jestem tym samym chłopcem, który opuścił pałac. Twój syn zmarł dawno temu. Wyglądam podobnie do twojego syna, ale moja cała świadomość jest inna. Popatrz tylko.”
        Ojciec rzekł: “Widzę to. Przez pół godziny, obrażam cię i wymyślam, to jest dostateczny dowód, że zmieniłeś się. Wiem, jaki byłeś porywczy: nie ustałbyś w takim spokoju? Co ci się przydarzyło?”
        Budda powiedział: “Opowiem ci. Najpierw chciałbym zobaczyć moją żonę i dziecko. Pewnie na mnie czekają. Słyszeli już zapewne, że przybywam.”
        Pierwszym, co powiedziała mu żona było: “Widzę, że jesteś zmieniony. Tych dwanaście lat było wielkim cierpieniem, nie dlatego, że odszedłeś, cierpiałam, bo nic mi nie powiedziałeś. Gdybyś mi powiedział, że idziesz na poszukiwanie prawdy, myślisz, że bym ci zabraniała? Obraziłeś mnie tym bardzo. Tę ranę noszę w sobie od tych dwunastu lat. Ja też należę do kasty wojowników. Myślisz, że jestem tak słaba, że płakałabym i krzyczała, żeby cię zatrzymać? Całych dwanaście lat cierpiałam dlatego, że nie zaufałeś mi. Pozwoliłabym ci. Pożegnała bym cię. Odprowadziła bym cię do rydwanu. Najpierw zadam ci jedno pytanie, jakie jest w moim umyśle od dwunastu lat... czy czegoś dostąpiłeś? Na pewno czegoś dostąpiłeś... nie jesteś tą samą osobą, która opuściła pałac, emanujesz innym światłem, twoja obecność jest nowa, świeża, oczy są czyste i jasne jak niebo bez chmur. Stałeś się piękny. Zawsze byłeś piękny, ale to piękno wydaje się być nie z tego świata. Jakby wdzięk z innego świata na ciebie zstąpił. Pytam więc, czegokolwiek dostąpiłeś, czy nie było to możliwe tu w pałacu? Czy pałac nie dopuszcza prawdy? To nadzwyczaj inteligentne pytanie, a Gautama Budda musiał się zgodzić.
        Mogłem dostąpić tego i tutaj, ale wtedy tego nie wiedziałem. Teraz mogę powiedzieć, że mogłem dostąpić tego tu w tym pałacu. Nie było potrzeby iść w góry czy dokądkolwiek. Doszedłem do swego wnętrza, a mogło zdarzyć się to wszędzie. Ten pałac był tak samo dobry jak inne miejsce, a teraz wiem, że wtedy nie miałem o tym pojęcia. Musisz mi więc wybaczyć, bo nie chodzi o to, że nie ufam tobie czy twojej odwadze. To ja wątpiłem w siebie, gdybym zobaczył cię obudzoną, gdybym zobaczył to dziecko, mógłbym zacząć się zastanawiać: “Co robię, zostawiam moją piękną żonę, jej miłość i totalne oddanie. Zostawiam moje jednodniowe dziecko... skoro mam odejść, po co dawałem mu życie?” Uciekam od swoich odpowiedzialności. Gdyby mój stary ojciec obudził się, nie byłoby to możliwe. Nie to, że ci nie ufam - tak naprawdę nie ufałem sobie. Wiedziałam, że byłoby wahanie. Nie byłem w wyrzeczeniu totalny. Jakaś moja cząstka mówiła:” Co robisz?” Inna mówiła: “czas to zrobić. Jeśli nie zrobisz tego teraz będzie to trudniejsze. Twój ojciec chce cię ukoronować, kiedy zostaniesz ogłoszony królem będzie trudniej.”
        Yashodhara powiedziała do niego: Oto, jedyne pytanie, które chciałam ci zadać. Jestem ogromnie szczęśliwa, że jesteś pełny prawdy, mówiąc, że mogłeś tego dostąpić gdziekolwiek. Oto, twój syn tu stoi, chłopiec co ma dwanaście lat, stale o ciebie pytał, a ja mówiłam mu: “Czekaj. On wróci, nie jest tak okrutny, tak niegrzeczny i nieludzki. Pewnego dnia wróci. Może to, czego mu potrzeba zajmie trochę czasu, ale gdy to urzeczywistni pierwszym co zrobi będzie powrót”. O to jest twój syn, a ja chcę cię zapytać - jaką spuściznę zostawisz swojemu synowi? Co masz mu dodania? Dałeś mu życie - co teraz mu dasz?
        Budda nie miał nic, tylko miskę żebraczą. Zawołał więc do syna o imieniu Rahul. Zawołał Rahula blisko siebie i dał mu tę miskę żebraczą mówiąc:
        -   Nic nie mam. To mój jedyny majątek; od tej pory będę musiał używać rąk jako miski żebraczej na jedzenie, gdy będę o nie prosił. Dając ci tę miskę, inicjuję cię do sannyasu. To jedyny skarb, jaki znalazłem  - i chciałbym, byś i ty go znalazł.
        Rzekł do Yashodhary:
        -  Musisz być gotowa, by stać się częściej częścią mojej komuny sannyasinów - i inicjował swoją żonę. Całą scenę obserwował ojciec, który rzekł do Gautama Buddy:
         Dlaczego mnie pomijasz? Nie chcesz dzielić się ze swoim starym ojcem, tym, co znalazłeś? Moja śmierć jest bardzo blisko ... inicjuj i mnie.
         Budda powiedział:
        - W istocie rzeczy przybyłem tu tylko po to, by zabrać was ze sobą, ponieważ to, co znalazłem jest znacznie większym królestwem - takim, które będzie trwać wiecznie, którego nie można podbić. Przybyłem tu, abyście mogli odczuć moją obecność, to co urzeczywistniłem, i abym mógł was nakłonić, byśmy razem wędrowali.`,
        explantation_sound: "/Explantation Sound/33.OdnowaExplantation.mp3",
    },
    {
        image: "/Images/57.Inteligencja.jpg",
        parable_text: `Rabia i zagadka zgubionej igły.
        Rodzimy się, by żyć w błogości. To nasze prawo naturalne. Ludzie są jednak tak głupi, że nawet nie domagają się tego, co jest ich naturalnym prawem. Bardziej interesują się tym, co mają inni i zaczynają zabiegać o te rzeczy. Nie patrzą do swego wnętrza, nie szukają we własnym domu. Człowiek inteligentny zaczyna poszukiwania od swego wnętrza. Człowiek inteligentny zaczyna poszukiwania od swego wewnętrznego istnienia. To jego pierwsze badania, bo dopóki nie pozna siebie, jak może szukać w świecie. Świat jest tak ogromny... A ten kto szuka wewnątrz znajduje natychmiast. To nie jest jakiś stopniowy proces, ale nagłe zjawisko, nagłe oświecenie.`,
        parable_sound: "/Parable Sound/57.InteligencjaParable.mp3",
        explantation_text: `Żyła kiedyś bardzo wielka mistyczka Sufi Rabia al-Adawia. Któregoś wieczoru ludzie zobaczyli, jak szuka ona czegoś na drodze. Była starą kobietą, oczy miała słabe trudno było jej patrzeć. Sąsiedzi przyszli jej więc pomóc. 
        - Czego szukasz ? - zapytali. 
        - To nieważne, ja tylko szukam - odpowiedziała Rabia. Jeżeli możecie mi pomóc, pomóżcie.
        - Rabia ,oszalałaś ? Mówisz, że nasze pytanie jest nieważne, ale jeżeli nie wiemy, czego szukasz, jak mamy ci pomóc ? - zapytali śmiejąc się. 
        - Dobrze tylko po to, żeby was zaspokoić, powiem, że szukam igły, zgubiłam igłę  - rzekła. 
        Zaczęli jej pomagać, ale uświadomili sobie, że droga jest wielka.  Igła to coś bardzo małego. Zapytali, więc Robię:
        - Powiedz nam, gdzie ją zgubiłaś, gdzie dokładnie. Bez tego trudno nam będzie. Droga jest wielka, możemy szukać i szukać. Gdzie ją zgubiłaś ?
        - Znowu niepotrzebne pytanie - rzekła Rabia. 
        - Co to ma wspólnego z moimi poszukiwaniami? 
        - Naprawdę oszalałaś - zatrzymali się. 
        - Dobrze tylko po to, żeby was zaspokoić, powiem, że zgubiłam ją w domu - powiedziała.
        - Czemu więc szukasz tutaj? - zapytali.
        - Ponieważ tutaj jest światło, a wewnątrz światła nie ma - podobno odpowiedział Rabia. Słońce zachodziło, na drodze, nadal było trochę światła. 
        Ta przypowieść jest bardzo znacząca. Czy zastanawiałeś się, czego szukasz ? Czy kiedykolwiek dokonywałeś głębokiej medytacji, by poznać, czego szukasz ? Nie. Nawet jeśli w jakiś krótkich ulotnych chwilach miałeś przeczucie,czego szukasz, nigdy nie było to dokładne, pewne. Nie określiłeś tego.  Jeśli spróbujesz to zdefiniować, im bardziej będziesz to robić, tym bardziej będziesz czuć, że nie ma potrzeby samego poszukiwania. Poszukiwania można prowadzić tylko w stanie niejasności śnienia; gdy sprawy nie są wyjaśnione, szukasz. Popychany jakimś wewnętrznym impulsem, poczuciem pilności, wiesz, że musisz szukać. To taka wewnętrzna potrzeba. Ale nie wiesz, czego szukasz.
        Dopóki nie dowiesz się, czego szukasz - jak możesz to znaleźć? To takie niejasne, myślisz, że to pieniądze, władza, prestiż, poszanowanie. A potem widzisz ludzi szanowanych, mających władzę... oni też szukają. Widzisz ludzi ogromnie bogatych, oni też szukają. Do samego końca życia szukają. Bogactwo więc nie pomoże, ani władza. Poszukiwania trwają bez względu na to, co masz. 
        Poszukiwania muszą więc dotyczyć czegoś innego. Nazwy, etykiety, pieniądze, władza, prestiż służą tylko uspokojeniu umysłu. Są tylko po to, by dopomóc ci poczuć, że czegoś szukasz. To coś nadal jest nieokreślone, jest niejasnym przeczuciem. 
        Pierwszą sprawą dla prawdziwego poszukującego, który stał się nieco świadomy, jest zdefiniowanie poszukiwania; sformułowanie wyraźnej koncepcji, określenie, czego dotyczy; doprowadzenie tego do śniącej świadomości, spojrzenie w to i zmierzenie się z tym. Natychmiast zaczyna się przemiana. Gdy zaczniesz definiować poszukiwania, tracisz nimi zainteresowanie. Im lepiej zdefiniowany przedmiot poszukiwań, tym jest go mniej. Gdy dokładnie wiesz, co to jest, nagle zniknie. Istnieje tylko wtedy, gdy nie zwracasz na niego dość uwagi. 
        Powtórzę: poszukiwanie istnieje tylko wtedy, gdy śpisz; tylko wtedy, gdy nie jesteś uważny. Nieświadomość stwarza poszukiwania. 
        Rabia ma rację. Wewnątrz nie ma światła. Ponieważ wewnątrz nie ma światła i świadomości, szukasz na zewnątrz - bo na zewnątrz wszystko wydaje się być wyraźniejsze. 
        Nasze zmysły są ekstrawertyczne. Oczy otwarte są na zewnątrz, ręce poruszają się na zewnątrz, nogi poruszają się w marszu na zewnątrz, uszy słuchają zewnętrznych hałasów i dźwięków. Cokolwiek jest ci dostępne, wszystko otwiera się na zewnątrz; wszystkich pięć zmysłów żyje ekstrawertyczne. Zaczynasz szukać tam, gdzie widzisz, czujesz, dotykasz - światło zmysłów pada na zewnątrz... a poszukujący jest wewnątrz. 
        Trzeba zrozumieć tę dychotomię. Poszukujący jest wewnątrz, a ponieważ światło jest na zewnątrz, poszukujący staje się ambitny, próbuje znaleźć na zewnątrz coś, co dałoby mu spełnienie. 
        Tak się nigdy nie stanie i nigdy tak nie było. Nie może tak być w samej naturze wszystkiego, gdyż dopóki nie znajdziesz poszukującego, wszystkie poszukiwania nie mają znaczenia. Dopóki nie poznasz, kim jesteś, wszystko, czego szukasz jest próżne, gdyż nie znasz poszukującego. Nie znając poszukującego, jak możesz właściwie działać, iść w dobrym kierunku ? Niemożliwe. Najpierw trzeba zająć się sprawami najważniejszymi.
        Gdy ustanie wszelkie poszukiwanie i staniesz się świadomy, że jest tylko jedno, co trzeba poznać - "Kim jest ten poszukujący we mnie ? Czym jest ta energia, którą chce szukać ? Kim Jestem ?" - następuje przemiana. Wszystkie wartości nagle się zmieniają. Zaczynasz żyć wewnątrz.
        Rabia nie będzie wtedy siedziała na drodze i szukała igły zgubionej gdzieś w ciemności własnej, wewnętrznej duszy. Gdy zaczniesz żyć wewnątrz... Na początku jest tam bardzo ciemno, Rabia ma rację. Jest bardzo, bardzo ciemno, bo przez całe żywoty nigdy nie byłeś wewnątrz, twoje oczy były skupione na świecie zewnętrznym. 
        Zauważyłeś? Gdy czasem z bardzo słonecznej drogi, gdzie jest jaskrawe światło, nagle wejdziesz do domu, jest bardzo ciemno, ponieważ oczy są skupione na świetle na zewnątrz. Gdy jest dużo światła źrenice oczu kurczą się. W ciemności oczy muszą odpoczywać. Jeżeli jednak nieco dłużej posiedzisz, stopniowo ciemność znika. Jest więcej światła. Oczy się przyzwyczajają. 
        Od wielu żywotów jesteś na zewnątrz, w gorącym w słońcu, w świecie - gdy wchodzisz do wewnątrz, zupełnie zapominasz, jak dostosować oczy. Medytacja nie jest niczym innym, jak właśnie dostosowaniem wzroku. A jeśli stale patrzysz do wewnątrz ( potrzeba na to trochę czasu ), stopniowo zaczniesz odczuwać to piękne, wewnętrzne światło. Nie jest ono agresywne, nie przypomina słońca, bardziej wygląda jak księżyc. Nie błyszczy, nie oślepia, jest bardzo zimne; nie jest gorące, jest bardzo współczujące, kojące, jak balsam. 
        Powoli, gdy dostosujesz się do wewnętrznego światła, zaczniesz widzieć, że to ty jesteś źródłem. Poszukujący jest tym, co jest poszukiwane. Wtedy zobaczysz, że skarb jest w tobie, a problemem było tylko to, że szukałeś go na zewnątrz. Szukałeś go gdzieś na zewnątrz, a on zawsze był w tobie. Szukałeś w niewłaściwym kierunku - tylko tyle.`,
        explantation_sound: "/Explantation Sound/57.InteligencjaExplantation.mp3"
    },
    {
        image: "/Images/41.Niepowodzenie.jpg",
        parable_text: `Jawny sekret prawdziwego sukcesu. 
        Kiedy jest poranek, jest poranek. Kiedy jest wieczór, jest wieczór. Nie ma wybierania. Porzuć wybieranie, a wszędzie będziesz wolny. Wolność można znaleźć tylko wtedy, gdy nie ma wybierania. Kiedy więc jesteś młody, jest pięknie; kiedy jesteś dzieckiem, jest pięknie, kiedy jesteś stary, jest pięknie; kiedy umierasz, jest pięknie -  ponieważ nigdy nie jesteś oddzielony od całości, jesteś jedynie falą na oceanie. 
        Fala na oceanie może zacząć myśleć o sobie jako o czymś oddzielnym, ale wtedy pojawią się kłopoty. Fala na oceanie nigdy nie myśli o sobie jako o czymś oddzielnym, kiedy więc ocean chce ją wziąść do siebie, jest skora, radosna, tańcząc, idzie do niego.`,
        parable_sound: "/Parable Sound/41.NiepowodzenieParable.mp3",
        explantation_text: `Pieśni Mistyka Kabira:
        Rozmawiam z mą wewnętrzną ukochaną, pytając, skąd pośpiech?
        Czujemy, że jest jakiś rodzaj ducha
        Który kocha ptaki i zwierzęta i mrówki - 
        Może ten sam, który nadaje ci promienność 
        W łonie twojej matki. 
        Logiczne przecież, że chodziłbyś 
        Teraz całkiem osierocony? 
        Prawdą jest, żeś odwrócił się od siebie. 
        I postanowił samemu w ciemności wędrować. 
        Teraz jesteś zaplątany w innych i zapomniałeś 
        To, coś kiedyś wiedział, 
        I to dlatego we wszystkim, co robisz 
        Jest ukryte jakieś dziwne niepowodzenie. 
        
        Wszystko dzieje się wtedy, gdy jest potrzebne; wszystko musi się dziać wtedy, gdy jest potrzebne. Wszystko jest dobrze, ty tylko ufaj. Pamiętaj o tej różnicy. Teolog powie: "Wierz w koncepcję Boga", Mistyk powie, że nie trzeba wierzyć w koncepcję Boga, wystarczy czuć harmonię w egzystencji. Nie jest to koncepcja, jakieś wierzenie -  możesz to odczuć, jest wszędzie. Jest niemal namacalne. 
        Gdy tylko pomyślisz, że jesteś jednością z całością, następuje odprężenie, nagłe zharmonizowanie wszystkiego ze wszystkim. Nie musisz mieć się na baczności, możesz się odprężyć. Nie trzeba utrzymywać napięcia, ponieważ nie ma przed tobą żadnego celu postawionego, tylko tobie. Płyniesz z Bogiem. Cel Boga jest twoim celem, jego przeznaczenie jest twoim przeznaczeniem. Nie masz swojego oddzielnego przeznaczenia, prywatne przeznaczenie sprowadza problemy. 
        Zauważyłeś to w swoim życiu ? Wszystko, co robisz, kończy się niepowodzeniem. Jednak tego nie widzisz, myślisz, że nie zrobiłeś czegoś tak jak należało i stąd niepowodzenie. Próbujesz więc czegoś innego i znów fiasko. Potem myślisz, że nie masz dość umiejętności, uczysz się więc czegoś i znów niepowodzenie. Potem myślisz, że "cały świat jest przeciwko mnie" albo że "los mi nie sprzyja", albo że "jestem ofiarą ludzkiej zazdrości". Wynajdujesz wyjaśnienia, dlaczego zawiodłeś, lecz nigdy nie docierasz do prawdziwego podłoża niepowodzenia. 
        Kabir mówi: niepowodzenie to ty-minus-Bóg. To wyjaśnienie Kabira: niepowodzenie równa się ty-minus-Bóg, a sukces jest równy ty-plus-Bóg. Sukces jest w Bogu i z Bogiem. Pamiętaj: mówiąc "Bóg", nie mam na myśli kogoś siedzącego gdzieś w niebie, ale ducha kosmosu. Czuj ducha kosmosu,Tao, prawo przenikające całą egzystencję - z niego jesteś zrodzony i do niego pewnego dnia wrócisz.`,
        explantation_sound: "/Explantation Sound/41.NiepowodzenieExplantation.mp3"
    },
    {
        image: "/Images/14.Autentyczność.jpg",
        parable_text: `Milarepa i fałszywy nauczyciel. 
        Ścieżka nie jest czymś rzeczywistym, rzeczywista jest autentyczność poszukującego. Podkreślam to - możesz podróżować dowolną ścieżką. Jeśli jesteś szczery i autentyczny, dotrzesz do celu. Niektóre ścieżki są twarde, inne są łatwiejsze, mogą mieć zieleń po obu stronach, mogą prowadzić pustynią, mieć wokoło piękne krajobrazy, a jeszcze inne biegną pustkowiem - to nie jest ważne. Jeśli jesteś szczery, uczciwy, autentyczny i prawdziwy, każda ścieżka prowadzi do celu. 
        Można więc to sprowadzić do tego, że autentyczność jest ścieżką. Bez względu na ścieżkę, którą idziesz, jeśli jesteś autentyczny, każda ścieżka prowadzi do celu. Odwrotność też jest prawdziwa: bez względu na ścieżkę, którą podążasz, jeśli nie jesteś autentyczny, nigdzie nie dojdziesz. Twoja autentyczność prowadzi cię do domu, nic innego. Wszystkie ścieżki są jedynie pomocą. Podstawą jest bycie autentycznym, prawdziwym.`,
        parable_sound: "/Parable Sound/14.AutentycznośćParable.mp3",
        explantation_text: `Kiedy Milarepa udał się do swego Mistrza w Tybecie, był tak pokorny tak czysty i autentyczny, że inni uczniowie zaczęli być zazdrośni. Było oczywiste, że zostanie sukcesorem. Pojawiła się oczywiście polityka, chcieli go zabić. Pewnego dnia uczniowie zwrócili się do niego. 
        - Jeśli naprawdę wierzysz w Mistrza, czy skoczysz z urwiska? Jeśli naprawdę wierzysz, jeśli ufasz żadne zło ci się nie stanie.
        Milarepa skoczył, nie wahając się ani chwili. Uczniowie popędzili na dół... była to przepaść na prawie tysiąc metrów. Zeszli na dół, by odnaleźć rozrzucone kości, a on siedział tam w pozycji lotosu ogromnie szczęśliwy. Otworzył oczy i rzekł:
        - Macie rację - ufność chroni. 
        Pomyśleli, że to na pewno jakiś przypadek, gdy więc któregoś dnia płonął dom rzekli do niego:
        - Jeśli kochasz Mistrza i ufasz, idź w ogień. 
        Pobiegł by ratować kobietę i dziecko, którzy zostali w środku. Pożar był tak wielki, że spodziewali się, że on zginie, ale tak się nie stało. Ufność uczyniła go jeszcze bardziej promiennym. 
        Wędrując kiedyś, mieli przeprawić się przez rzekę, uczniowie rzekli do niego: 
        - Ty nie potrzebujesz płynąć łodzią. Masz tak wielką ufność - możesz pójść po wodzie. 
        I Milarepa poszedł po wodzie. Wtedy Mistrz po raz pierwszy go zobaczył. Nie wiedział, że kazano mu skakać na dno doliny nie, wchodzić do płonącego domu. Wtedy jednak stał na brzegu rzeki i widział, jak Milarepa idzie po wodzie, zapytał go więc: 
        - Co ty robisz? To przecież niemożliwe!
        - Nic nie jest niemożliwe! Czynię to dzięki twojej mocy, Mistrzu - odrzekł Milarepa. 
        Mistrz pomyślał sobie: "Skoro moję imię i moja moc działają dla takiego ignoranta, głupca... Nigdy sam nie spróbowałem'. Spróbował i utonął. Od tamtej pory już nikt o nim nie słyszał.`,
        explantation_sound: "/Explantation Sound/14.AutentycznośćExplantation.mp3"
    },
    {
        image: "/Images/15.Uważność.jpg",
        parable_text: `Nagła śmierć ucznia aikido. 
        Bądź uważny. Każda chwila musi być przyjmowana tak, jakby była ostatnią. Może tak być, że to będzie ostatnia chwila, wykorzystaj ją więc totalnie. Wykorzystaj ją więc totalnie. Wyciśnij z niej ostatnie soki. W tej ogromnej totalności będziesz uważny.`,
        parable_sound: "/Parable Sound/15.UważnośćParable.mp3",
        explantation_text: `Japoński Mistrz Ekido był surowym nauczycielem i uczniowie bali się go. Pewnego dnia jeden z uczniów wybijał godzinę gongiem świątyni. Nagle zgubił jedno uderzenie, spojrzał bowiem na piękną dziewczynę przekraczającą bramy świątyni. Uczeń tego nie wiedział, ale Ekido stał za nim. Ekido uderzył ucznia kijem. Siła uderzenia zatrzymała serce ucznia, który zmarł. Dawny zwyczaj, według którego uczeń oddawał swoje życie mistrzowi pozostał jedynie czystą formalnością. Ekido został więc przez ludzi uznany za skompromitowanego. 
        Po tym zdarzeniu od Ekido wyszło dziesięciu oświeconych sukcesorów, liczba niezwykle duża. Gdy czytasz tę opowieść, możesz myśleć, że Mistrz zabił swojego ucznia. Tak nie jest. Uczeń i tak był gotów umrzeć, a to była chwila jego śmierci. Mistrz to wiedział po prostu wykorzystał chwilę śmierci dla oświecenia ucznia. Nie mówi się tu tego, ale musiało tak być. Skąd Mistrz wiedziałby, że ma stanąć za uczniem? Czy nie miał nic ważniejszego do robienia? W tamtej chwili nie było nic bardziej istotnego - uczeń i tak miał umrzeć, a jego śmierć musiała być wykorzystana. To piękna i bardzo znacząca opowieść. Uczeń widział przechodzącą piękną dziewczynę i cała jego świadomość została zagubiona. Jego całe istnienie stało się pragnieniem, chciał pójść za tą dziewczyną, posiąść ją. Jeszcze przed chwilą był uważny, a teraz już nie. Uderzał w Gong w pełni uważności. Jest to część medytacji w klasztorach Zen: Cokolwiek robisz, bądź w tym jako światło, a wszystko się odkryje przed tobą. Tak więc ten uczeń w chwili śmierci miał być uważny i czujny, a umysł robił ostatnie co mógł - pojawiła się piękna dziewczyna.!
        Gdy uczeń zgubił uważność, Mistrz go uderzył. Mistrz widzi niewidzialną śmierć: uderza tylko po to, by uczynić ucznia uważnym. Mistrz czekał za jego plecami. Mistrzowie zawsze czekają za plecami uczniów fizycznie lub nie. Nadchodząca śmierć to jedna z najważniejszych chwil. Mistrz uderzył ucznia z całej siły. Jego ciało padło, ale w sobie stał się uważny. Pragnienie znikło. Wszystko pozostało razem z ciałem, rozbite w pył, uczeń stał się uważny. Umarł w tej uważności. Jeśli uda się połączyć uważność i śmierć - musisz dostąpić oświecenia.`,
        explantation_sound: "Explantation Sound/15.UważnośćExplantation.mp3"
    },
    {
        image: "/Images/22.GłupieSerce.jpg",
        parable_text: `Szalona mądrość Franciszka z Asyżu.
        Serce ma własne powody wszystkich reakcji, których umysł nie może zrozumieć. Serce ma własny wymiar istnienia, który jest całkowicie niewidoczny dla umysłu. Serce jest wyższe i głębsze niż umysł, jest poza jego zasięgiem. Wygląda to głupio miłość zawsze wygląda głupio. Miłość zawsze wygląda głupawo, gdyż miłość jest, gdyż miłość nie jest utylitarna. Umysł jest utylitarny. Wszystko wykorzystuje do czegoś innego: to jest znaczenie utylitarności. Umysł ma jakiś cel, jest nastawiony na dążenie do celu, wszystko zamienia w środki, a miłości nie można zamienić w jakiś środek prowadzący do czegoś innego. Miłość sama w sobie jest celem.`,
        parable_sound: "/Parable Sound/22.GłupieSerceParable.mp3",
        explantation_text: `Głupcy zawsze mają w sobie jakąś subtelną mądrość, a mądrzy ludzie zawsze zachowują się jak głupcy. 
        W dawnych czasach wszyscy wielcy władcy mieli na dworze jednego głupca. Mieli wielu mędrców, doradców, ministrów i premierów, ale zawsze był też jeden głupiec. Dlaczego? Ponieważ są sprawy, których tak zwani mędrcy nie zrozumieją, które tylko głupi człowiek może zrozumieć - ponieważ tak zwani mądrzy ludzie są tak głupi, że ich przebiegłość i spryt zamykają im umysły. 
        Głupiec jest człowiekiem prostym, a był potrzebny, bo często tak zwani mądrzy ludzie nie powiedzą czegoś, gdyż boją się cesarza. Głupiec nikogo się nie boi mówi bez względu na konsekwencje. Tak zachowują się głupcy: wprost bez myślenia, bez względu na skutki. Człowiek przebiegły zawsze najpierw myśli o skutkach, a dopiero potem działa. Myśl przychodzi pierwsza, potem działanie. Głupi człowiek działa myśl nie przychodzi pierwsza. 
        Gdy ktoś urzeczywistnia to, co Najwyższe, jest inny niż wszyscy tacy mędrcy. Nie jest taki jak oni. Może przypominać głupców, ale nie będzie podobny do mędrców. 
        Gdy Święty Franciszek dostąpił oświecenia, nazywał siebie "głupcem Boga". Papież był człowiekiem mądrych ludzi, a gdy Święty Franciszek pojechał do niego, nawet on pomyślał, że ten człowiek oszalał. Sam był inteligentny, kalkulujący i sprytny... jak inaczej mógłby być papieżem? Aby stać się papieżem, trzeba przejść przez tyle polityki, potrzebna jest dyplomacja, konkurencyjna agresja do odsuwania innych na bok, wykorzystania innych po drodze i wyrzucenia potem. To polityka... papież jest bowiem szefem polityki. Religia jest drugorzędna, albo nic nie znacząca. Jak człowiek religijny może walczyć i być agresywny na tym stanowisku? To tylko politycy. 
        Święty Franciszek pojechał do papieża, a papież pomyślał, że ten człowiek był głupcem -  ale drzewa i ptaki i ryby myślą inaczej. Gdy Święty Franciszek poszedł nad rzekę ryby wyskakiwały z wody, ciesząc się, że  Franciszek do nich przyszedł. Tysiące ludzi to widziało. Miliony ryb równocześnie wyskakiwały w powietrze; rzeka pełna była skaczących ryb. Przyszedł Święty Franciszek i ryby były szczęśliwe. Gdziekolwiek poszedł, ptaki leciały za nim; podlatywały i siedziały mu na nodze, na jego ciele i kolanach. Rozumiały, że głupiec jest lepszy niż papież. Nawet drzewa, które wyschły i miały umrzeć, stawały się zielone i znów rozkwitały, gdy święty Franciszek zbliżał się do nich. Te drzewa dobrze rozumiały, że ten głupiec nie był zwyczajnym głupcem - był głupcem Boga.`,
        explantation_sound: "Explantation Sound/22.GłupieSerceExplantation.mp3"
    },
    {
        image: "/Images/60.Śmiech.jpg",
        parable_text: `Ostatnia niespodzianka chińskiego mistyka.
        Śmiech jest wieczny, życie jest wieczne, świętowanie trwa. Aktorzy zmieniają się, ale dramat trwa. Fale zmieniają się, ale ocean trwa. Śmiejesz się, zmieniasz się, ktoś inny śmieje się - śmiech trwa. Świętujesz, ktoś inny świętuje - świętowanie trwa. Egzystencja jest ciągłością, jest continuum. Nie ma w niej ani jednej przerwy. Żadna śmierć nie jest śmiercią, bo każda śmierć otwiera nowe drzwi, to początek. Życie nie ma końca, zawsze jest jakiś nowy początek, zmartwychwstanie. Jeżeli zmienisz swój smutek, w świętowanie będziesz też w stanie zmienić swoją śmierć w zmartwychwstanie. Tak uczy się sztuki; póki jeszcze jest czas.
        `,
        parable_sound: "/Parable Sound/60.ŚmiechParable.mp3",
        explantation_text: `Było trzech chińskich mistyków. Nikt nie zna ich imion. Znani byli jako Trzej Śmiejący Się Święci, ponieważ nigdy niczego innego nie robili - tylko się śmiali. 
        Ci trzej ludzie byli naprawdę piękni, gdy tak się śmiali i trzęsły im się brzuchy. Stawało się to zaraźliwe i inni zaczynali się śmiać. Całe targowisko zaczynało się. Jeszcze przed paru chwilami był to brzydki plac, gdzie ludzie myśleli tylko o pieniądzach także, nagle przyszli ci trzej szaleńcy i zmienili jakość całego targowiska. Zapomnieli, że przybyli kupować i sprzedawać. Nikt nie przejmował się chciwością. Na parę sekund otworzył się nowy świat. 
        Wędrowali po całych Chinach, pomagając ludziom śmiać się. Smutni ludzie, rozzłoszczeni, chciwi, zazdrośni ludzie - wszyscy zaczynali śmiać się razem z nimi. Wielu ludzi poznało ten klucz, że możesz się przemienić. 
        W którejś wiosce jeden z tej trójki zmarł. Ludzie z wioski zebrali się i powiedzieli: "Teraz będzie kłopot. Pewnie zobaczymy, jak oni się nie śmieją. Zmarł ich przyjaciel. Na pewno będą płakać". Ale gdy przyszedł odpowiedni czas tych dwóch tańczyło, śmiało się i świętowało jego śmierć. Ludzie z wioski powiedzieli: "Tego już za wiele. Gdy ktoś umiera, śmiech i taniec, to profanacja". Odpowiedzieli na to: "Całe życie śmialiśmy się razem z nim. Jak możemy go pożegnać czymkolwiek innym ?  Musimy się śmiać, cieszyć i świętować. To jedyne pożegnanie możliwe dla kogoś, kto śmiał się całe życie. Dla nas nie jest on martwy. Jak może śmiech umrzeć, jak może życie umrzeć ?".
        Gdy ciało miało zostać spalone, ludzie z wioski powiedzieli: "Wykąpiemy go zgodnie z obrządkiem". Dwaj jego przyjaciele rzekli jednak: "Nie, nasz przyjaciel powiedział: Żadnych obrządków, nie przebierajcie mnie i nie kąpcie. Połóżcie mnie na stosie tak jak jestem. Musimy więc przestrzegać jego poleceń". 
        Nagle nastąpiło wielkie wydarzenie. Starzec zrobił ostatni dowcip: pod szatami ukrył sztuczne ognie i gdy ciało podpalono, nagle zrobiło się święto! Cała wioska zaczęła się śmiać. Tych dwóch szalonych przyjaciół tańczyło, potem cała wioska zaczęła tańczyć. To nie była śmierć, było to nowe życie.`,
        explantation_sound: "/Explantation Sound/60.ŚmiechExplantation.mp3"
    },
    {
        image: "/Images/52.Skrucha.jpg",
        parable_text: `Gdy Shibli rzucił różę
        Jeżeli zrobiłeś coś złego, idź do tej osoby. Bądź pokorny i poproś ją o przebaczenie. Tylko ten człowiek może cię wybaczyć, nikt inny. Pamiętaj, że znaczeniem słowa "grzech" jest zapomnienie. Nie zapominaj więc i nie powtarzaj tego w przyszłości, bo twoje proszenie o wybaczenie straci znaczenie. Bądź czujny, uważny i świadomy i nigdy już tego nie rób. Pamiętaj, aby nie popełniać znowu tego samego błędu - taka powinna być decyzja w tobie, wtedy naprawdę odczuwasz skruchę. 
        Skrucha może stać się bardzo, bardzo głęboka, jeśli zrozumiesz odpowiedzialność. Wtedy nawet coś drobnego, jeżeli stanie się skruchą nie tylko w słowach, nie tylko na powierzchni - jeżeli dociera to głęboko do twoich korzeni, czujesz skruchę w samych swoich korzeniach, całe twoje istnienie drży i płacze, i płyną łzy nie tylko z twoich oczu, ale z każdej komórki twojego ciała -  wtedy skrucha może stać się przemianą.`,
        parable_sound: "/Parable Sound/52.SkruchaParable.mp3",
        explantation_text: `Pierwszy raz poznano imię Shibli, gdy zamordowano Mansoora al-Hillal. Wielu ludzi zostało zamordowanych przez tak zwanych ludzi religijnych, choćby Jezus, ale nigdy nie było takiego morderstwa, jakie zdarzyło się w przypadku al-Hillaj. Najpierw odcięto mu nogi, ale on żył. Wtedy odcięto mu ręce. Potem odcięto mu język, wykłuto oczy, ale on ciągle żył. Pocięto jego ciało na kawałki. 
        Jakie przestępstwo popełnił Mansoor? Powiedział tylko: An'al Hak, co oznacza "jestem Prawdą, jestem Bogiem". Wszyscy mędrcy Upaniszadów to mówią:  Aham Brahmasmi, jestem Brahmą, Najwyższą Jaźnią. Mahometanie nie mogli tego znieść. 
        Mansoor jest jednym z największych Sufich. Gdy zaczęto odcinać mu ręce, popatrzył w niebo, modlił się do Boga i rzekł: "Nie oszukasz mnie ! Widzę cię we wszystkich tych ludziach, jesteś tu. Próbujesz mnie oszukać ? Przychodzisz jako morderca ? Jako wróg ? A ja ci mówię, w jakiejkolwiek formie przyjdziesz, poznam cię, bo już poznałem cię w sobie. Teraz mnie nie oszukasz".
        Shibli był przyjacielem al-Hillaj. Ludzie rzucali kamienie i błoto i śmiali się, Shibli stał obok. Mansoor śmiał się. Nagle zaczął płakać, gdy Shibli  rzucił w niego różą. Ktoś zapytał: "Co się stało? Śmiałeś się, gdy rzucaliśmy kamienie, oszalałeś ?  Shibli rzucił tylko kwiat róży. Czemu teraz płaczesz ?". 
        Mansoor powiedział : "Ci, którzy rzucają kamienie, nie wiedzą, co robią, ale Shibli wie. Bóg będzie miał wielkie trudności, by mu to wybaczyć.. Innym będzie wybaczone, bo działają w niewiedzy, nie można nic na to poradzić. W swojej ślepocie tylko to mogą zrobić. Shibli wie ! Dlatego płaczę za niego. To jedyna osoba, która tu popełnia grzech".
        To zdanie Mansoora całkowicie odmieniło Shibli. Rzucił Koran, święte pisma i rzekł: "Nie pomogły mi one w zrozumieniu, cała ta wiedza jest bezużyteczna. Teraz będę szukał właściwej wiedzy". Potem zapytany, dlaczego rzucił kwiatem, odparł: "Bałem się tłumu, gdybym niczym nie rzucił, ludzie mogliby myśleć, że należę do grupy Mansoora. Mogli zwrócić się przeciwko mnie. Nie mogłem rzucić kamieniem, bo wiem, że Mansoor jest niewinny. Nie mogłem też nabrać odwagi i niczym nie rzucić. Rzuciłem więc kwiatem, kompromis. Mansoor miał rację, płakał nade mną, nad moim strachem, tchórzostwem. Płakał, ponieważ poszedłem na kompromis z tłumem". 
        Shibli odmienił się całkowicie. Zrozumiał. Płacz Mansoora stał się jego przemianą.`,
        explantation_sound: "Explantation Sound/52.SkruchaExplantation.mp3"
    },
    {
        image: "/Images/35.PanowanieNadNastrojami.jpg",
        parable_text: `Sekret pierścienia. 
        Myślenie, że "jestem umysłem" - to brak uważności. Poznanie, że umysł jest tylko mechanizmem takim samym jak ciało, że jest czymś oddzielnym... Noc przychodzi, poranek przychodzi - nie utożsamiasz się z nocą. Nie mówisz "jestem nocą" czy "jestem dniem". Noc przychodzi, poranek, dzień, znowu noc: koło kręci się stale, ale ty bądź uważny tego, że nie jesteś tymi zjawiskami. Tak samo jest z umysłem. Złość przychodzi, ale ty zapominasz - stajesz się złością. Chciwość przychodzi, zapominasz -  stajesz się chciwością. Nienawiść przychodzi i znów zapominasz - stajesz się nienawiścią. Na tym polega brak uważności. 
        Uważność jest obserwowaniem, że umysł jest pełny chciwości, złości, nienawiści czy pożądania, ale ty tylko obserwujesz. Wtedy zaczynasz dostrzegać jak narasta chciwość, jak staje się wielkim ciemnym obłokiem, a potem znika - a ty pozostajesz nietknięty. Jak długo tak możesz trwać ? Twoja złość jest chwilowa, chciwość i pożądanie też są chwilowe. Patrz tylko, a zdziwisz się - to przychodzi i odchodzi. Ty pozostajesz nietknięty, chłodny i spokojny. 
        Najbardziej podstawowa sprawa to pamiętanie, że kiedy jesteś w dobrym nastroju w ekstazie, nie myśl, że tak już będzie na stałe. Żyj chwilą tak radośnie, jak to możliwe, wiedząc, że przyszła i odejdzie jak wiatr wchodzący do twego domu z całym aromatem i świeżością - wychodzący zaraz drugimi drzwiami. 
        To najważniejsze, myśląc o zatrzymaniu swych ekstatyczny chwil już zacząłeś je niszczyć. Gdy przychodzą, bądź wdzięczny egzystencji, gdy odchodzą bądź wdzięczny. Bądź otwarty. Zdarzy się to wiele razy, nie oceniaj, nie wybieraj. 
        Owszem będą chwile, gdy będziesz w niedoli. Co z tego ? Są ludzie cierpiący, którzy nigdy nie zaznali nawet chwili ekstazy, a ty masz szczęście. Nawet w niedoli, pamiętaj, że nie będzie ona trwać wiecznie. Przeminie, nie daj się więc wtrącić jej z równowagi. Bądź odprężony. Jak dzień i noc są chwile radości i chwile smutku: akceptuj je jako część dualizmu natury, ot, biegu życia. 
        Jesteś tylko obserwatorem: nie stajesz się szczęściem ani niedolą. Szczęście przychodzi i odchodzi, niedola przychodzi i odchodzi. Jedno trwa zawsze: obserwator, świadek. Stopniowo obserwator staje się coraz bardziej scentrowany. Dni i noce przychodzą... narodziny przychodzą i śmierci przychodzą.... sukces nadejdzie, niepowodzenie nadejdzie. Gdy jesteś zcentrowany w obserwatorze - gdyż jest to jedyna rzeczywistość w tobie - wszystko jest zjawiskiem przemijającym. 
        Choć przez chwilę spróbuj poczuć to, co mówię: bądź tylko obserwatorem. Nie zatrzymuj żadnej chwili, ponieważ jest piękna i nie odpychaj żadnej chwili dlatego, że jest pełna cierpienia. Przestań to robić. Przez całe żywoty to robisz. Jeszcze ci się to nie udało i nigdy się nie uda. 
        Jedynym sposobem jest wyjście poza to, pozostanie poza tym, znalezienie miejsca, z którego można obserwować wszystkie te zmieniające się zjawiska bez utożsamienia.`,
        parable_sound: "/Parable Sound/35.PanowanieNadNastrojamiParable.mp3",
        explantation_text: `Król zażądał kiedyś od mędrców na dworze: 
        - Robiony jest dla mnie piękny pierścień. Mam jeden z największych diamentów. Chce w pierścieniu zachować ukryte przesłanie, które może mi pomóc w nagłej potrzebie. Musi być bardzo małe, by dało się je ukryć pod diamentem w pierścieniu. 
        Byli tam sami mędrcy, wielcy uczeni potrafiący pisać olbrzymie traktaty. Ale podać przesłanie mające dwa lub trzy słowa, które mogłoby pomóc w chwili nagłej potrzeby... Myśleli, patrzyli w swe księgi, ale nic nie mogli znaleźć. 
        Król miał starego sługę, którego traktował niemal jak ojca, był bowiem też jego sługą. Matka króla wcześnie zmarła, sługa opiekował się nim nie był więc to zwykły sługa. Król bardzo go szanował.
        - Nie jestem mądry, ani wykształcony, ale znam takie przesłanie, bo jest ono tylko jedno - rzekł starzec. - Ci ludzie nie mogą ci go dać, może dać je tylko mistyk, ktoś, kto sam je urzeczywistnił. Przez całe moje długie życie w pałacu spotykałem różnych ludzi, a kiedyś spotkałem tu mistyka. On też był gościem twojego ojca, a mnie oddano na jego posługi. Gdy wyjeżdżał, w geście podziękowania za wszystkie moje usługi, dał mi to przesłanie. 
        Sługa napisał je na małym kawałku papieru, złożył go i powiedział do króla. 
        - Nie  czytaj go, zachowaj je ukryte w pierścieniu. Otwórz go tylko wtedy, gdy wszystko inne zawiedzie, gdy nie będzie już żadnego wyjścia. 
        Taki czas nadszedł wkrótce. Kraj został zaatakowany i król stracił swe królestwo. Uciekał konno, by ocalić życie, ścigali go jeźdźcy wroga. On był sam, a ich było wielu.  Dojechał do miejsca, gdzie kończyły się wszystkie ścieżki... urwisko i głęboka przepaść. Gdyby w nią wpadł, byłby to jego koniec. Nie mógł zawrócić, wróg był tuż za nim, słyszał dźwięk podków ich koni. Nie mógł jechać dalej... niebyło już żadnego innego sposobu. Przypomniał sobie o pierścieniu. Otworzył go, wyjął papier. Było tam maleńkie przesłanie o wielkiej wartości, które brzmiało po prostu: "To też minie". Wielka Cisza nastała, gdy król przeczytał to zdanie. "To też minie" I minęło. 
        Wszystko mija, nic w tym świecie nie trwa takie samo. Wrogowie ścigający go musieli widocznie zgubić drogę w lesie, pojechali gdzieś indziej, bo odgłosy kopyt stopniowo ucichły. Król był ogromnie wdzięczny słudze i nieznanemu mistykowi. Te słowa sprawiły cud. Złożył papier, włożył go z powrotem do pierścienia, zebrał swe wojska i odzyskał królestwo. Gdy wjeżdżał do stolicy jako zwycięzca było wielkie święto - wszystko w całym mieście, muzyka, tańce, a on był bardzo dumny z siebie. 
        Przy jego rydwanie szedł starzec, który rzekł: 
        - Teraz też jest to prawdą - spójrz na to przesłanie jeszcze raz. 
        - Co ty mówisz ? - rzekł król - teraz jestem zwycięzcą, ludzie świętują. Nie jestem już w rozpaczy, w sytuacji bez wyjścia.
        -  Słuchaj, panie. Ten święty powiedział mi, że to przesłanie nie jest tylko na czas rozpaczy, ale też na czas przyjemności. Nie tylko na czas klęski, ale też na czas zwycięstwa, nie tylko wtedy, gdy jesteś ostatni, ale też wtedy, gdy jesteś pierwszy.
        Król otworzył pierścień, przeczytał przesłanie: "To też minie"... nagle taki sam spokój, taka sama cisza pośród tłumów, cieszących się, świętujących, tańczących...tylko teraz znikły duma i ego. 
        Wszystko przemija. 
        Król zaprosił starego sługę do rydwanu.
        - Czy jest coś więcej ? - zapytał go. - Wszystko przemija... twoje przesłanie bardzo mi pomogło. 
        Starzec odpowiedział: 
        Trzecie co ten święty powiedział, to "Pamiętaj, wszystko przemija. Tylko ty trwasz; trwaj wiecznie jako świadek".
        Wszystko przemija, ale ty trwaj. Jesteś rzeczywistością: wszystko inne jest tylko snem. Są piękne sny i są koszmary... Nie ma znaczenia, czy to piękny sen czy koszmar, istotny jest ten, kto widzi te sny - on jest jedyną rzeczywistością.`,
        explantation_sound: "Explantation Sound/35.PanowanieNadNastrojamiExplantation.mp3"
    },
]